#!/usr/bin/env python3
"""Generate ready-to-paste Antigravity scheduled-task prompts.

The two editorial routines (SELECT, WRITE) are defined once, canonically, in
ROUTINE_PROMPT_A.md and ROUTINE_PROMPT_B.md. A Claude Code Routine auto-creates
its own branch and pushes; an Antigravity/Gemini agent needs to be told the
concrete git steps instead. Rather than duplicate the ~340 lines of prompt into
a second file that could silently drift (the stale-prompt bug that has bitten
this project twice), this script CONCATENATES the canonical prompt with a small
git tail and writes the paste-ready task files.

Regenerate any time the canonical prompts change:

    python antigravity/build_tasks.py

Then re-paste the two TASK_*.md files into the two Antigravity scheduled tasks.
"""
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "antigravity"

# The git tail. It assumes the Antigravity task's GitHub credentials are already
# configured for push (via Antigravity's GitHub connection or a fine-grained PAT
# set up as a git credential helper) — so NO token ever appears in this text.
# Each task does a fresh clone of main (so WRITE always sees the latest
# feeds/selected/), writes its one file, and pushes to a dated gemini/** branch.
# select.yml and publish.yml both trigger on gemini/** (see PR widening the
# workflow filters), so the full-text-fetch and publish stages then run exactly
# as they do for the Claude flow.
GIT_TAIL = """

---

## Running as an Antigravity scheduled task — do these steps around the work above

Your GitHub credentials for `AmanBeni/daily-cactus` are already configured for
push. NEVER print, echo, or paste any token into your output.

1. Start with a fresh clone of `main` and work inside it:

       git clone https://github.com/AmanBeni/daily-cactus.git repo
       cd repo

2. Use the value of the `date` field inside `{input_file}` as `<today>` for the
   output filename — do NOT compute the date yourself, so the filename always
   matches the day's data.

3. Do the editorial work exactly as instructed above (read {reads}, write
   `{output_file}`).

4. Publish that one file and then STOP — do nothing else:

       git add {output_file}
       git -c user.name="Gemini Routine" -c user.email="gemini@dailycactus.local" \\
           commit -m "{commit_msg}"
       git push origin HEAD:gemini/{branch_kind}-<today>

The concrete steps in this section replace the vague "push to your branch"
line in the instructions above.
"""

TASKS = {
    "TASK_A_SELECT.md": {
        "src": "ROUTINE_PROMPT_A.md",
        "input_file": "feeds/digest_lean.json",
        "reads": "`feeds/digest_lean.json` + `TASTE.md`",
        "output_file": "selections/<today>.json",
        "commit_msg": "Selections <today>",
        "branch_kind": "select",
    },
    "TASK_B_WRITE.md": {
        "src": "ROUTINE_PROMPT_B.md",
        "input_file": "feeds/selected/<today>.json",
        "reads": "`feeds/selected/<today>.json` + `TASTE.md`",
        "output_file": "drafts/<today>.json",
        "commit_msg": "Edition <today>",
        "branch_kind": "write",
    },
}

BANNER = ("<!-- AUTOGENERATED by antigravity/build_tasks.py from {src}. Do not "
          "edit by hand — edit the canonical prompt and re-run the script. -->\n\n")


def main():
    for out_name, cfg in TASKS.items():
        body = (ROOT / cfg["src"]).read_text()
        tail = GIT_TAIL.format(**cfg)
        (OUT / out_name).write_text(BANNER.format(src=cfg["src"]) + body + tail)
        print(f"wrote antigravity/{out_name}  (from {cfg['src']})")


if __name__ == "__main__":
    main()
